### ISSUE TITLE
Add link to github on project homepage

### ISSUE THREAD

**Issue by davelab6** [impallari/The-Lobster-Font#1]
I suggest http://www.impallari.com/lobster links here :)

**Comment by davelab6** [comment]
@impallari this takes 30 seconds to do; go to https://github.com/impallari/The-Lobster-Font/ and at the top is a grey 'edit' link, click that and add the link :)

**Comment by davelab6** [comment]
Ping :)

**Comment by impallari** [comment]
Done. The new lobster page is now https://impallari.com/fonts/lobster/
