### ISSUE TITLE
"iv" looks convincingly like a "w"

### ISSUE THREAD

**Issue by controversial** [impallari/The-Lobster-Font#3]
In the original Lobster font, the letters `iv` consecutively look a lot like a `w`.
![iv](https://cloud.githubusercontent.com/assets/10377391/15951182/2f9a9056-2e84-11e6-8463-a75fc692c392.png)

This is even worse with Lobster 2: 
![screenshot 2016-06-08 at 9 20 17 pm](https://cloud.githubusercontent.com/assets/10377391/15951211/6d4d4e16-2e84-11e6-869d-18e6b2320ccb.png)

Not sure if there's a solution for this, but just wanted to make sure you were aware of this potential impact on readability

**Comment by impallari** [comment]
Yep, I'm aware. A consequence of the style.
