### ISSUE TITLE
Percent

### ISSUE THREAD

**Issue by m4rc1e** [impallari/The-Lobster-Font#6]
Hey @alexeiva,

I also noticed the same problem in the percent.

old:
![screen shot 2016-11-11 at 11 44 20](https://cloud.githubusercontent.com/assets/7525512/20212593/55a86a80-a804-11e6-8d1a-865662b67192.png)

new:
![screen shot 2016-11-11 at 11 44 14](https://cloud.githubusercontent.com/assets/7525512/20212599/585d2036-a804-11e6-81cb-fb87eb1f47f1.png)

I'm more than happy to revert this.

**Comment by alexeiva** [comment]
check out https://github.com/impallari/The-Lobster-Font/pull/7

**Comment by impallari** [comment]
Thanks!
